### ISSUE TITLE
inquiry about the data resources

### ISSUE THREAD

**Issue by yixiangD** [beckyvan156/antibioticsGNN#1]
Hi,
I am very interested in this topic.
I wonder if you could provide any reference to the data presented in this repo.
Thanks so much!

**Comment by zhanxw** [comment]
Thanks for your interest. The data are a collection of several studies. Some are private and we may need to remove them in the further analysis. For a public set of data related to our previous work, please check this: https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1007511

**Comment by yixiangD** [comment]
Sounds good. Thanks for the quick clarifications. I just checked the paper and found the link to the data access is "Not Found". Could you check if that's the case? thanks!
